-- ─────────────────────────────────────────────────────────────────────────────
-- Students Biodata Migration
-- Adds all admission-form fields to the `students` table.
--
-- The PHP import page (admin/import-students.php) runs this automatically
-- on first load via ensureBiodataColumns(), so this file is for manual
-- DB setup / reference / rollback only.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE `students`
  ADD COLUMN IF NOT EXISTS `gr_no`              VARCHAR(30)   DEFAULT NULL COMMENT 'General Register / GR Number',
  ADD COLUMN IF NOT EXISTS `kuickpay_id`        VARCHAR(30)   DEFAULT NULL COMMENT 'Kuickpay student/consumer ID',
  ADD COLUMN IF NOT EXISTS `category`           VARCHAR(30)   DEFAULT NULL COMMENT 'Admission category (e.g. AOB 1, AOG 2)',
  ADD COLUMN IF NOT EXISTS `academic_group`     VARCHAR(50)   DEFAULT NULL COMMENT 'Academic stream/group (Science, Arts, Pre-Medical, Commerce)',
  ADD COLUMN IF NOT EXISTS `child_order`        TINYINT       DEFAULT NULL COMMENT 'Birth order in family (1=first, 2=second, etc.)',
  ADD COLUMN IF NOT EXISTS `domicile`           VARCHAR(100)  DEFAULT NULL COMMENT 'Domicile province/district',
  ADD COLUMN IF NOT EXISTS `permanent_address`  TEXT          DEFAULT NULL COMMENT 'Permanent home address (present address stored in address column)',
  ADD COLUMN IF NOT EXISTS `emergency_phone`    VARCHAR(20)   DEFAULT NULL COMMENT 'Emergency contact phone number',
  ADD COLUMN IF NOT EXISTS `whatsapp_no`        VARCHAR(20)   DEFAULT NULL COMMENT 'WhatsApp contact number',
  ADD COLUMN IF NOT EXISTS `religion`           VARCHAR(50)   DEFAULT NULL COMMENT 'Religion',
  ADD COLUMN IF NOT EXISTS `sect`               VARCHAR(50)   DEFAULT NULL COMMENT 'Sect / denomination',
  ADD COLUMN IF NOT EXISTS `blood_group`        VARCHAR(5)    DEFAULT NULL COMMENT 'Blood group (A+, A-, B+, B-, O+, O-, AB+, AB-)',
  ADD COLUMN IF NOT EXISTS `last_school`        VARCHAR(200)  DEFAULT NULL COMMENT 'Last school / institution attended before admission',
  ADD COLUMN IF NOT EXISTS `nationality`        VARCHAR(100)  DEFAULT NULL COMMENT 'Nationality',
  ADD COLUMN IF NOT EXISTS `father_occupation`  VARCHAR(150)  DEFAULT NULL COMMENT 'Father / guardian occupation',
  ADD COLUMN IF NOT EXISTS `documents_submitted` TEXT         DEFAULT NULL COMMENT 'Documents submitted at admission (B-Form, Report Card, etc.)',
  ADD COLUMN IF NOT EXISTS `medical_info`       TEXT          DEFAULT NULL COMMENT 'Medical history: chronic conditions, allergies, medications, immunizations',
  ADD COLUMN IF NOT EXISTS `skills`             TEXT          DEFAULT NULL COMMENT 'Student skills (comma-separated)',
  ADD COLUMN IF NOT EXISTS `sports`             TEXT          DEFAULT NULL COMMENT 'Sports / co-curricular activities',
  ADD COLUMN IF NOT EXISTS `awards`             TEXT          DEFAULT NULL COMMENT 'Awards, certificates, achievements';

-- Note: ADD COLUMN IF NOT EXISTS requires MySQL 8.0+ or MariaDB 10.3+.
-- For older MySQL 5.7, run each ADD COLUMN separately after checking SHOW COLUMNS.

-- ─────────────────────────────────────────────────────────────────────────────
-- Backfill biodata for the 20 BMC2025 dummy students (house, gr_no, etc.)
-- Safe to run on a fresh install — ignored if user_id not found.
-- ─────────────────────────────────────────────────────────────────────────────

UPDATE students SET house_id=1, gr_no='GR-25-001', kuickpay_id='KP201001', category='AOB 1', academic_group='Science', child_order=2, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='B+', last_school='Beaconhouse School Lahore', nationality='Pakistani', permanent_address='Village Manga Mandi, Kasur', emergency_phone='03009998877', whatsapp_no='03001112233', father_occupation='Business', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025001');
UPDATE students SET house_id=3, gr_no='GR-25-002', kuickpay_id='KP201002', category='AOG 1', academic_group='Science', child_order=1, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='O+', last_school='The City School Lahore', nationality='Pakistani', permanent_address='Mohalla Hussain Abad, Sheikhupura', emergency_phone='03008887766', whatsapp_no='03002223344', father_occupation='Teacher', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025002');
UPDATE students SET house_id=2, gr_no='GR-25-003', kuickpay_id='KP201003', category='AOB 2', academic_group='Science', child_order=3, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='A+', last_school='LGS DHA Lahore', nationality='Pakistani', permanent_address='Street 12, Sargodha Road, Faisalabad', emergency_phone='03007776655', whatsapp_no='03003334455', father_occupation='Army Officer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025003');
UPDATE students SET house_id=4, gr_no='GR-25-004', kuickpay_id='KP201004', category='AOG 2', academic_group='Arts', child_order=2, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='A-', last_school='Punjab Group Lahore', nationality='Pakistani', permanent_address='Chak 12, District Nankana Sahib', emergency_phone='03006665544', whatsapp_no='03004445566', father_occupation='Shopkeeper', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025004');
UPDATE students SET house_id=1, gr_no='GR-25-005', kuickpay_id='KP201005', category='AOB 1', academic_group='Pre-Medical', child_order=1, domicile='Sindh', religion='Islam', sect='Sunni', blood_group='B-', last_school='Karachi Grammar School', nationality='Pakistani', permanent_address='Village Sehwan, Dadu', emergency_phone='03005554433', whatsapp_no='03005556677', father_occupation='Govt. Officer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025005');
UPDATE students SET house_id=3, gr_no='GR-25-006', kuickpay_id='KP201006', category='AOG 1', academic_group='Science', child_order=2, domicile='Sindh', religion='Islam', sect='Shia', blood_group='O-', last_school='St. Josephs Convent Karachi', nationality='Pakistani', permanent_address='Mohalla Askari, Hyderabad', emergency_phone='03004443322', whatsapp_no='03006667788', father_occupation='Doctor', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025006');
UPDATE students SET house_id=2, gr_no='GR-25-007', kuickpay_id='KP201007', category='AOB 2', academic_group='Commerce', child_order=4, domicile='Sindh', religion='Islam', sect='Sunni', blood_group='AB+', last_school='Habib Public School Karachi', nationality='Pakistani', permanent_address='Town Khairpur Mirs', emergency_phone='03003332211', whatsapp_no='03007778899', father_occupation='Business', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025007');
UPDATE students SET house_id=4, gr_no='GR-25-008', kuickpay_id='KP201008', category='AOG 2', academic_group='Arts', child_order=1, domicile='Sindh', religion='Islam', sect='Sunni', blood_group='A+', last_school='Roots International Karachi', nationality='Pakistani', permanent_address='Village Mirpur Khas, Sindh', emergency_phone='03002221100', whatsapp_no='03008889900', father_occupation='Farmer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025008');
UPDATE students SET house_id=1, gr_no='GR-25-009', kuickpay_id='KP201009', category='AOB 1', academic_group='Science', child_order=2, domicile='KPK', religion='Islam', sect='Sunni', blood_group='B+', last_school='Army Public School Peshawar', nationality='Pakistani', permanent_address='Village Charsadda, KPK', emergency_phone='03001110099', whatsapp_no='03009990011', father_occupation='Businessman', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025009');
UPDATE students SET house_id=3, gr_no='GR-25-010', kuickpay_id='KP201010', category='AOG 1', academic_group='Pre-Medical', child_order=3, domicile='KPK', religion='Islam', sect='Sunni', blood_group='O+', last_school='Peshawar Model School', nationality='Pakistani', permanent_address='Mardan Road, Swabi, KPK', emergency_phone='03009998877', whatsapp_no='03010001122', father_occupation='Teacher', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025010');
UPDATE students SET house_id=2, gr_no='GR-25-011', kuickpay_id='KP201011', category='AOB 2', academic_group='Commerce', child_order=1, domicile='KPK', religion='Islam', sect='Sunni', blood_group='A-', last_school='Edwardes College Peshawar', nationality='Pakistani', permanent_address='Village Landi Kotal, Khyber', emergency_phone='03008887766', whatsapp_no='03011112233', father_occupation='Police Officer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025011');
UPDATE students SET house_id=4, gr_no='GR-25-012', kuickpay_id='KP201012', category='AOG 2', academic_group='Arts', child_order=2, domicile='KPK', religion='Islam', sect='Sunni', blood_group='B-', last_school='Islamia Collegiate Peshawar', nationality='Pakistani', permanent_address='Town Dir Upper, KPK', emergency_phone='03007776655', whatsapp_no='03012223344', father_occupation='Doctor', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025012');
UPDATE students SET house_id=1, gr_no='GR-25-013', kuickpay_id='KP201013', category='ASB 1', academic_group='Pre-Medical', child_order=2, domicile='Balochistan', religion='Islam', sect='Sunni', blood_group='AB-', last_school='Divisional Public School Quetta', nationality='Pakistani', permanent_address='Town Turbat, Balochistan', emergency_phone='03006665544', whatsapp_no='03013334455', father_occupation='Govt. Officer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025013');
UPDATE students SET house_id=3, gr_no='GR-25-014', kuickpay_id='KP201014', category='ASG 1', academic_group='Science', child_order=1, domicile='Balochistan', religion='Islam', sect='Sunni', blood_group='O-', last_school='Quetta Grammar School', nationality='Pakistani', permanent_address='Town Khuzdar, Balochistan', emergency_phone='03005554433', whatsapp_no='03014445566', father_occupation='Engineer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025014');
UPDATE students SET house_id=2, gr_no='GR-25-015', kuickpay_id='KP201015', category='ASB 2', academic_group='Commerce', child_order=3, domicile='Balochistan', religion='Islam', sect='Sunni', blood_group='A+', last_school='Bolan Medical School Quetta', nationality='Pakistani', permanent_address='Village Mastung, Balochistan', emergency_phone='03004443322', whatsapp_no='03015556677', father_occupation='Farmer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025015');
UPDATE students SET house_id=4, gr_no='GR-25-016', kuickpay_id='KP201016', category='ASG 2', academic_group='Arts', child_order=2, domicile='Balochistan', religion='Islam', sect='Sunni', blood_group='B+', last_school='Govt. Girls School Quetta', nationality='Pakistani', permanent_address='Village Pishin, Balochistan', emergency_phone='03003332211', whatsapp_no='03016667788', father_occupation='Shopkeeper', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025016');
UPDATE students SET house_id=1, gr_no='GR-25-017', kuickpay_id='KP201017', category='ASB 1', academic_group='Pre-Medical', child_order=1, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='O+', last_school='Roots School Islamabad', nationality='Pakistani', permanent_address='Street 5, Rawalpindi Cantt', emergency_phone='03002221100', whatsapp_no='03017778899', father_occupation='Advocate', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025017');
UPDATE students SET house_id=3, gr_no='GR-25-018', kuickpay_id='KP201018', category='ASG 1', academic_group='Science', child_order=2, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='A+', last_school='FG College for Women Islamabad', nationality='Pakistani', permanent_address='Mohalla Ali Pur, Attock', emergency_phone='03001110099', whatsapp_no='03018889900', father_occupation='Army Officer', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025018');
UPDATE students SET house_id=2, gr_no='GR-25-019', kuickpay_id='KP201019', category='ASB 2', academic_group='Commerce', child_order=4, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='B-', last_school='IMCB G-9/4 Islamabad', nationality='Pakistani', permanent_address='Village Gujar Khan, Rawalpindi', emergency_phone='03009998877', whatsapp_no='03019990011', father_occupation='Businessman', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025019');
UPDATE students SET house_id=4, gr_no='GR-25-020', kuickpay_id='KP201020', category='ASG 2', academic_group='Arts', child_order=1, domicile='Punjab', religion='Islam', sect='Sunni', blood_group='AB+', last_school='FGEI Cantonment, Rawalpindi', nationality='Pakistani', permanent_address='Street 9, Chakwal Town', emergency_phone='03008887766', whatsapp_no='03020001122', father_occupation='Professor', documents_submitted='B-Form, TC, Report Card', medical_info='Nil' WHERE user_id=(SELECT id FROM users WHERE user_id='BMC2025020');
