<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../../config/config.php';

$user = requireAuth('student_affairs');
$db   = getDB();

$classId    = (int)($_GET['class_id'] ?? 0);
$dateFilter = $_GET['date'] ?? date('Y-m-d');
$viewMode   = $_GET['view'] ?? 'daily';

if (!$classId) { redirect('/portal/student-affairs/attendance.php'); }

$className = '';
$clRow = $db->prepare('SELECT name FROM classes WHERE id = ?');
$clRow->execute([$classId]);
$className = ($clRow->fetch()['name'] ?? '');

$attendance = [];

if ($viewMode === 'summary') {
    $st = $db->prepare(
        'SELECT u.name, s.roll_no,
                COUNT(a.id) AS total,
                SUM(a.status="P") AS present,
                SUM(a.status="A") AS absent,
                SUM(a.status="L") AS `leave`
         FROM students s
         JOIN users u ON u.id = s.user_id
         LEFT JOIN attendance a ON a.student_id = s.id
         WHERE s.class_id = ?
         GROUP BY s.id, u.name, s.roll_no
         ORDER BY s.roll_no'
    );
    $st->execute([$classId]);
    $attendance = $st->fetchAll();
} else {
    $st = $db->prepare(
        'SELECT u.name, s.roll_no, a.status, a.date, sub.name AS subject_name
         FROM attendance a
         JOIN students s   ON s.id = a.student_id
         JOIN users u      ON u.id = s.user_id
         LEFT JOIN subjects sub ON sub.id = a.subject_id
         WHERE s.class_id = ? AND a.date = ?
         ORDER BY s.roll_no'
    );
    $st->execute([$classId, $dateFilter]);
    $attendance = $st->fetchAll();
}

$viewLabel  = $viewMode === 'summary' ? 'Summary' : ('Daily — ' . date('d M Y', strtotime($dateFilter)));
$filename   = 'Attendance_' . preg_replace('/[^A-Za-z0-9_]/', '_', $className) . '_' . ($viewMode === 'summary' ? 'Summary' : $dateFilter) . '.doc';

header('Content-Type: application/msword');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-cache, no-store, must-revalidate');
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<title>Attendance — <?= h($className) ?></title>
<!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View></w:WordDocument></xml><![endif]-->
<style>
  body { font-family: Arial, sans-serif; font-size: 11pt; margin: 2cm; }
  h2 { color: #1e3a5f; font-size: 14pt; margin-bottom: 4pt; }
  p.meta { font-size: 9pt; color: #666; margin-bottom: 12pt; }
  table { width: 100%; border-collapse: collapse; font-size: 10pt; }
  th { background: #1e3a5f; color: #fff; padding: 5px 8px; text-align: left; }
  td { border: 1px solid #ccc; padding: 4px 8px; }
  tr:nth-child(even) td { background: #f5f5f5; }
  .center { text-align: center; }
  .present { color: #166534; font-weight: bold; }
  .absent  { color: #991b1b; font-weight: bold; }
  .leave   { color: #854d0e; font-weight: bold; }
</style>
</head>
<body>
<h2>Attendance Report — <?= h($className) ?> | <?= h($viewLabel) ?></h2>
<p class="meta">Generated: <?= date('d M Y, H:i') ?> &nbsp;|&nbsp; Generated by: <?= h($user['name']) ?></p>

<?php if (empty($attendance)): ?>
<p>No attendance records found.</p>
<?php elseif ($viewMode === 'summary'): ?>
<table>
  <thead>
    <tr><th>Roll</th><th>Name</th><th class="center">Total</th><th class="center">Present</th><th class="center">Absent</th><th class="center">Leave</th><th class="center">%</th></tr>
  </thead>
  <tbody>
    <?php foreach ($attendance as $a):
      $pct = $a['total'] > 0 ? round($a['present'] / $a['total'] * 100, 1) : 0;
    ?>
    <tr>
      <td><?= h($a['roll_no']) ?></td>
      <td><?= h($a['name']) ?></td>
      <td class="center"><?= $a['total'] ?></td>
      <td class="center present"><?= $a['present'] ?></td>
      <td class="center absent"><?= $a['absent'] ?></td>
      <td class="center leave"><?= $a['leave'] ?></td>
      <td class="center"><?= $pct ?>%</td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<?php else: ?>
<table>
  <thead>
    <tr><th>Roll</th><th>Name</th><th>Subject</th><th class="center">Status</th></tr>
  </thead>
  <tbody>
    <?php foreach ($attendance as $a):
      $sl = match($a['status']) {'P'=>'Present','A'=>'Absent','L'=>'Leave',default=>$a['status']};
      $sc = match($a['status']) {'P'=>'present','A'=>'absent','L'=>'leave',default=>''};
    ?>
    <tr>
      <td><?= h($a['roll_no']) ?></td>
      <td><?= h($a['name']) ?></td>
      <td><?= h($a['subject_name'] ?: '—') ?></td>
      <td class="center <?= $sc ?>"><?= $sl ?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<?php endif; ?>
</body>
</html>
